### ISSUE TITLE
Update to seed 0.5

### ISSUE THREAD

**Issue by TatriX** [seed-rs/seed-quickstart-webpack#7]
Hi! First of all thank you for the amazing project!

Are you working on updating this quickstart to `seed 0.5`?  If so, could you be so kind to give us any ETA? I'd like to use this template as a basis for a new project and I wonder, should I wait a bit for an updated version or do the transition myself.

**Comment by MartinKavik** [comment]
Hi, thanks! 
WIP, I want to release it today.

**Comment by MartinKavik** [comment]
New version released.

OT: @TatriX Let me be your website monitor: _"Your Let's Encrypt certificate for domain tatrix.org expired 08-12-2019. Connection to rogalia.ru is not secure. Link to vincent.is is dead."_ 😄

**Comment by TatriX** [comment]
Thanks ;)
